--------------------------------------------------------
--  File created - zondag-april-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "HENK2"."ACCOUNTS" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CURSUSSEN
--------------------------------------------------------

  CREATE TABLE "HENK2"."CURSUSSEN" 
   (	"ID" NUMBER, 
	"NAAM" VARCHAR2(20 BYTE), 
	"BESCHRIJVING" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "HENK2"."ROLES" 
   (	"ROLNAAM" VARCHAR2(20 BYTE), 
	"BESCHRIJVING" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HENK2.ACCOUNTS
SET DEFINE OFF;
Insert into HENK2.ACCOUNTS (USERNAME,PASSWORD,ROLE) values ('1','1','admin');
Insert into HENK2.ACCOUNTS (USERNAME,PASSWORD,ROLE) values ('2','22','student');
Insert into HENK2.ACCOUNTS (USERNAME,PASSWORD,ROLE) values ('3','3','student');
REM INSERTING into HENK2.CURSUSSEN
SET DEFINE OFF;
Insert into HENK2.CURSUSSEN (ID,NAAM,BESCHRIJVING) values ('1','PAFR','patterns and frameworks');
Insert into HENK2.CURSUSSEN (ID,NAAM,BESCHRIJVING) values ('2','SARCH','Software archichture');
REM INSERTING into HENK2.ROLES
SET DEFINE OFF;
Insert into HENK2.ROLES (ROLNAAM,BESCHRIJVING) values ('student','mag alleen lezen');
Insert into HENK2.ROLES (ROLNAAM,BESCHRIJVING) values ('admin','mag alles');
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENK2"."ROLES_PK" ON "HENK2"."ROLES" ("ROLNAAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CURSUSSEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENK2"."CURSUSSEN_PK" ON "HENK2"."CURSUSSEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACCOUNTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HENK2"."ACCOUNTS_PK" ON "HENK2"."ACCOUNTS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CURSUSSEN
--------------------------------------------------------

  ALTER TABLE "HENK2"."CURSUSSEN" MODIFY ("NAAM" NOT NULL ENABLE);
  ALTER TABLE "HENK2"."CURSUSSEN" ADD CONSTRAINT "CURSUSSEN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HENK2"."CURSUSSEN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "HENK2"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ROLNAAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HENK2"."ROLES" MODIFY ("ROLNAAM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "HENK2"."ACCOUNTS" ADD CONSTRAINT "ACCOUNTS_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HENK2"."ACCOUNTS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HENK2"."ACCOUNTS" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "HENK2"."ACCOUNTS" ADD CONSTRAINT "ACCOUNTS_FK1" FOREIGN KEY ("ROLE")
	  REFERENCES "HENK2"."ROLES" ("ROLNAAM") ON DELETE SET NULL ENABLE;
